import {
  Activity,
  ArrowRightLeft,
  CheckSquare,
  UserCog,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  MessageSquare,
  Flag,
  FlagOff,
  ShieldCheck,
  Pencil,
  Lock,
  Unlock,
  LogIn,
  LogOut,
  KeyRound,
  ShieldAlert,
  Image as ImageIcon,
  FileDown,
  Settings2,
  Workflow,
  ListChecks,
  Plug,
  Unplug,
  CalendarClock,
  RefreshCw,
} from "lucide-react"

export const ACTION_META: Record<string, { label: string; icon: typeof Activity; color: string }> = {
  "stage.move": { label: "Stage Move", icon: ArrowRightLeft, color: "#036638" },
  "checklist.toggle": { label: "Checklist", icon: CheckSquare, color: "#0F9B8E" },
  "assignment.change": { label: "Assignment", icon: UserCog, color: "#7C3AED" },
  "assignment.claim": { label: "Claim", icon: UserCheck, color: "#7C3AED" },
  "notes.update": { label: "Notes", icon: MessageSquare, color: "#6B7280" },
  "flag.create": { label: "Flag Raised", icon: Flag, color: "#DC2626" },
  "flag.clear": { label: "Flag Cleared", icon: FlagOff, color: "#16A34A" },
  "eligibility.check": { label: "Eligibility", icon: ShieldCheck, color: "#0891B2" },
  "patient.create": { label: "Patient Created", icon: UserPlus, color: "#036638" },
  "patient.update": { label: "Details Updated", icon: Pencil, color: "#6B7280" },
  "status.update": { label: "Status", icon: RefreshCw, color: "#D97706" },
  "lock.set": { label: "Locked", icon: Lock, color: "#D97706" },
  "lock.clear": { label: "Unlocked", icon: Unlock, color: "#16A34A" },
  "appointment.update": { label: "Appointment", icon: CalendarClock, color: "#D97706" },
  "auth.login": { label: "Login", icon: LogIn, color: "#2563EB" },
  "auth.login_failed": { label: "Failed Login", icon: ShieldAlert, color: "#DC2626" },
  "auth.logout": { label: "Logout", icon: LogOut, color: "#2563EB" },
  "auth.password_change": { label: "Password Changed", icon: KeyRound, color: "#2563EB" },
  "auth.password_reset_requested": { label: "Reset Requested", icon: KeyRound, color: "#2563EB" },
  "auth.password_reset_completed": { label: "Password Reset", icon: KeyRound, color: "#2563EB" },
  "profile.update": { label: "Profile Updated", icon: Pencil, color: "#7C3AED" },
  "profile.avatar_update": { label: "Avatar Changed", icon: ImageIcon, color: "#7C3AED" },
  "user_management.user_created": { label: "User Created", icon: UserPlus, color: "#0891B2" },
  "user_management.user_updated": { label: "User Updated", icon: UserCog, color: "#0891B2" },
  "user_management.user_deleted": { label: "User Deleted", icon: UserMinus, color: "#DC2626" },
  "user_management.user_activated": { label: "User Activated", icon: UserCheck, color: "#16A34A" },
  "user_management.user_deactivated": { label: "User Deactivated", icon: UserX, color: "#D97706" },
  "report.exported": { label: "Report Exported", icon: FileDown, color: "#0F9B8E" },
  "system.setting_updated": { label: "Settings", icon: Settings2, color: "#6B7280" },
  "system.stage_created": { label: "Stage Created", icon: Workflow, color: "#6B7280" },
  "system.stage_updated": { label: "Stage Updated", icon: Workflow, color: "#6B7280" },
  "system.stage_reordered": { label: "Stages Reordered", icon: Workflow, color: "#6B7280" },
  "system.stage_deleted": { label: "Stage Deleted", icon: Workflow, color: "#6B7280" },
  "system.checklist_item_created": { label: "Checklist Added", icon: ListChecks, color: "#6B7280" },
  "system.checklist_item_updated": { label: "Checklist Updated", icon: ListChecks, color: "#6B7280" },
  "system.checklist_item_deleted": { label: "Checklist Removed", icon: ListChecks, color: "#6B7280" },
  "system.eligibility_rule_created": { label: "Eligibility Rule", icon: ShieldCheck, color: "#6B7280" },
  "system.eligibility_rule_updated": { label: "Eligibility Rule", icon: ShieldCheck, color: "#6B7280" },
  "system.eligibility_rule_deleted": { label: "Eligibility Rule", icon: ShieldCheck, color: "#6B7280" },
  "system.crm_connected": { label: "CRM Connected", icon: Plug, color: "#6B7280" },
  "system.crm_disconnected": { label: "CRM Disconnected", icon: Unplug, color: "#6B7280" },
  "system.crm_permission_updated": { label: "CRM Permission", icon: Plug, color: "#6B7280" },
}

export const CATEGORY_META: Record<string, { label: string; color: string }> = {
  auth: { label: "Auth", color: "#2563EB" },
  profile: { label: "Profile", color: "#7C3AED" },
  patient: { label: "Patient", color: "#036638" },
  appointment: { label: "Appointment", color: "#D97706" },
  user_management: { label: "User Mgmt", color: "#0891B2" },
  report: { label: "Report", color: "#0F9B8E" },
  system: { label: "System", color: "#6B7280" },
}

export function actionMeta(action?: string | null) {
  return (action && ACTION_META[action]) || { label: action || "Activity", icon: Activity, color: "#6B7280" }
}

/** Full date + time, e.g. "Aug 13, 2026, 2:30 PM" */
export function fullDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  })
}
